# Copyright 2021 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

---
address:
  tcdm_start: 0x40000000
  tcdm_end: 0x40000008
  nr_cores: 0x40000010
  scratch_reg: 0x40000020
  wakeup_reg: 0x40000028
  barrier_reg: 0x40000038
  cluster_base_hartid: 0x40000040
  cluster_num: 0x40000048
  cluster_id: 0x40000050
  uart: 0xF00B8000
memory:
    -
        tcdm:
            start: 0x0
            end: 0x10000
            latency: 5
        periphs:
            start: 0x100000
            end: 0x10000c
            latency: 5
            callbacks:
                - name: semaphores
                  size: 12
        dram:
            start: 0x80000000
            end: 0x80010000
            latency: 10
        ext_tcdm:
            -
                cluster: 1
                start: 0x10000
    -
        tcdm:
            start: 0x0
            end: 0x20000
            latency: 5
        periphs:
            start: 0x100000
            end: 0x100000
            latency: 5
            callbacks: []
        dram:
            start: 0x80000000
            end: 0x80010000
            latency: 10
        ext_tcdm:
            -
                cluster: 0
                start: 0x20000
            -
                cluster: 2
                start: 0x30000
    -
        tcdm:
            start: 0x0
            end: 0x30000
            latency: 5
        periphs:
            start: 0x100000
            end: 0x100000
            latency: 5
            callbacks: []
        dram:
            start: 0x80000000
            end: 0x80010000
            latency: 10
        ext_tcdm: []

