# Copyright 2020 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
site_name: Snitch
theme:
  name: material

  icon:
    repo: fontawesome/brands/github

repo_url: https://github.com/pulp-platform/snitch
repo_name: pulp-platform/snitch

markdown_extensions:
- admonition
- def_list
- pymdownx.highlight
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
- Home: index.md
- User Guide:
  - Getting Started: ug/getting_started.md
  - Benchmarking: ug/benchmarking.md
  - Tooling Setup at IIS: ug/setup-iis.md
  - Trace Example: ug/example_trace.html
  - Docker: ug/docker.md
  - Directory Structure: ug/directory_structure.md
  - Documentation: ug/documentation.md
- Systems:
  - Snitch Cluster:
    - Guide: ug/snitch_cluster.md
    - Schema: schema-doc/snitch_cluster.md
  - Occamy:
    - Guide: ug/occamy_system/occamy.md
    - Architecture: ug/occamy_system/1_overview.md
      - Address Map: ug/occamy_system/2_addrmap.md
      - System Components: ug/occamy_system/3_system_components.md
      - Clocking: ug/occamy_system/4_clocking.md.md
      - Interrupts and Synchronization: 5_interrupts_and_synchronization.md.md
    - Schema: schema-doc/occamy.md
- Reference Manual:
  - Snitch: rm/snitch/index.md
  - Snitch Cluster: rm/snitch_cluster/index.md
  - Reqrsp Interface: rm/reqrsp_interface/index.md
  - Custom Instructions: rm/custom_instructions.md
- Snitch Runtime:
  - Pages: runtime/Pages/index.md
  - Files: runtime/Files/index.md
  - Classes: runtime/Classes/index.md
  - Examples: runtime/Examples/index.md
  - Modules: runtime/Modules/index.md
  - Namespaces: runtime/Namespaces/index.md
  # - Solder: rm/solder.md
- Publications: publications.md
