// Generated register defines for snitch_cluster_peripheral

// Copyright information found in source file:
// Copyright 2020 ETH Zurich and University of Bologna.

// Licensing information found in source file:
// Licensed under Solderpad Hardware License, Version 0.51, see LICENSE for
// details. SPDX-License-Identifier: SHL-0.51

#ifndef _SNITCH_CLUSTER_PERIPHERAL_REG_DEFS_
#define _SNITCH_CLUSTER_PERIPHERAL_REG_DEFS_

#ifdef __cplusplus
extern "C" {
#endif
// Number of performance counters
#define SNITCH_CLUSTER_PERIPHERAL_PARAM_NUM_PERF_COUNTERS 8

// Register width
#define SNITCH_CLUSTER_PERIPHERAL_PARAM_REG_WIDTH 64

// Enable particular performance counter and start tracking. (common
// parameters)
// Enable particular performance counter and start tracking.
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_0_REG_OFFSET 0x0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_0_CYCLE_0_BIT 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_0_TCDM_ACCESSED_0_BIT 1
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_0_TCDM_CONGESTED_0_BIT 2
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_0_ISSUE_FPU_0_BIT 3
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_0_ISSUE_FPU_SEQ_0_BIT 4
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_0_ISSUE_CORE_TO_FPU_0_BIT \
    5
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_0_RETIRED_INSTR_0_BIT 6
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_0_RETIRED_LOAD_0_BIT 7
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_0_RETIRED_I_0_BIT 8
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_0_RETIRED_ACC_0_BIT 9
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_0_DMA_AW_STALL_0_BIT 10
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_0_DMA_AR_STALL_0_BIT 11
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_0_DMA_R_STALL_0_BIT 12
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_0_DMA_W_STALL_0_BIT 13
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_0_DMA_BUF_W_STALL_0_BIT 14
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_0_DMA_BUF_R_STALL_0_BIT 15
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_0_DMA_AW_DONE_0_BIT 16
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_0_DMA_AW_BW_0_BIT 17
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_0_DMA_AR_DONE_0_BIT 18
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_0_DMA_AR_BW_0_BIT 19
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_0_DMA_R_DONE_0_BIT 20
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_0_DMA_R_BW_0_BIT 21
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_0_DMA_W_DONE_0_BIT 22
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_0_DMA_W_BW_0_BIT 23
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_0_DMA_B_DONE_0_BIT 24
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_0_DMA_BUSY_0_BIT 25
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_0_ICACHE_MISS_0_BIT 26
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_0_ICACHE_HIT_0_BIT 27
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_0_ICACHE_PREFETCH_0_BIT 28
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_0_ICACHE_DOUBLE_HIT_0_BIT \
    29
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_0_ICACHE_STALL_0_BIT 30

// Enable particular performance counter and start tracking.
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_1_REG_OFFSET 0x8
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_1_CYCLE_1_BIT 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_1_TCDM_ACCESSED_1_BIT 1
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_1_TCDM_CONGESTED_1_BIT 2
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_1_ISSUE_FPU_1_BIT 3
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_1_ISSUE_FPU_SEQ_1_BIT 4
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_1_ISSUE_CORE_TO_FPU_1_BIT \
    5
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_1_RETIRED_INSTR_1_BIT 6
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_1_RETIRED_LOAD_1_BIT 7
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_1_RETIRED_I_1_BIT 8
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_1_RETIRED_ACC_1_BIT 9
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_1_DMA_AW_STALL_1_BIT 10
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_1_DMA_AR_STALL_1_BIT 11
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_1_DMA_R_STALL_1_BIT 12
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_1_DMA_W_STALL_1_BIT 13
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_1_DMA_BUF_W_STALL_1_BIT 14
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_1_DMA_BUF_R_STALL_1_BIT 15
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_1_DMA_AW_DONE_1_BIT 16
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_1_DMA_AW_BW_1_BIT 17
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_1_DMA_AR_DONE_1_BIT 18
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_1_DMA_AR_BW_1_BIT 19
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_1_DMA_R_DONE_1_BIT 20
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_1_DMA_R_BW_1_BIT 21
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_1_DMA_W_DONE_1_BIT 22
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_1_DMA_W_BW_1_BIT 23
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_1_DMA_B_DONE_1_BIT 24
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_1_DMA_BUSY_1_BIT 25
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_1_ICACHE_MISS_1_BIT 26
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_1_ICACHE_HIT_1_BIT 27
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_1_ICACHE_PREFETCH_1_BIT 28
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_1_ICACHE_DOUBLE_HIT_1_BIT \
    29
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_1_ICACHE_STALL_1_BIT 30

// Enable particular performance counter and start tracking.
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_2_REG_OFFSET 0x10
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_2_CYCLE_2_BIT 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_2_TCDM_ACCESSED_2_BIT 1
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_2_TCDM_CONGESTED_2_BIT 2
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_2_ISSUE_FPU_2_BIT 3
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_2_ISSUE_FPU_SEQ_2_BIT 4
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_2_ISSUE_CORE_TO_FPU_2_BIT \
    5
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_2_RETIRED_INSTR_2_BIT 6
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_2_RETIRED_LOAD_2_BIT 7
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_2_RETIRED_I_2_BIT 8
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_2_RETIRED_ACC_2_BIT 9
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_2_DMA_AW_STALL_2_BIT 10
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_2_DMA_AR_STALL_2_BIT 11
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_2_DMA_R_STALL_2_BIT 12
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_2_DMA_W_STALL_2_BIT 13
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_2_DMA_BUF_W_STALL_2_BIT 14
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_2_DMA_BUF_R_STALL_2_BIT 15
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_2_DMA_AW_DONE_2_BIT 16
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_2_DMA_AW_BW_2_BIT 17
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_2_DMA_AR_DONE_2_BIT 18
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_2_DMA_AR_BW_2_BIT 19
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_2_DMA_R_DONE_2_BIT 20
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_2_DMA_R_BW_2_BIT 21
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_2_DMA_W_DONE_2_BIT 22
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_2_DMA_W_BW_2_BIT 23
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_2_DMA_B_DONE_2_BIT 24
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_2_DMA_BUSY_2_BIT 25
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_2_ICACHE_MISS_2_BIT 26
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_2_ICACHE_HIT_2_BIT 27
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_2_ICACHE_PREFETCH_2_BIT 28
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_2_ICACHE_DOUBLE_HIT_2_BIT \
    29
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_2_ICACHE_STALL_2_BIT 30

// Enable particular performance counter and start tracking.
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_3_REG_OFFSET 0x18
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_3_CYCLE_3_BIT 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_3_TCDM_ACCESSED_3_BIT 1
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_3_TCDM_CONGESTED_3_BIT 2
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_3_ISSUE_FPU_3_BIT 3
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_3_ISSUE_FPU_SEQ_3_BIT 4
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_3_ISSUE_CORE_TO_FPU_3_BIT \
    5
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_3_RETIRED_INSTR_3_BIT 6
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_3_RETIRED_LOAD_3_BIT 7
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_3_RETIRED_I_3_BIT 8
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_3_RETIRED_ACC_3_BIT 9
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_3_DMA_AW_STALL_3_BIT 10
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_3_DMA_AR_STALL_3_BIT 11
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_3_DMA_R_STALL_3_BIT 12
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_3_DMA_W_STALL_3_BIT 13
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_3_DMA_BUF_W_STALL_3_BIT 14
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_3_DMA_BUF_R_STALL_3_BIT 15
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_3_DMA_AW_DONE_3_BIT 16
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_3_DMA_AW_BW_3_BIT 17
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_3_DMA_AR_DONE_3_BIT 18
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_3_DMA_AR_BW_3_BIT 19
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_3_DMA_R_DONE_3_BIT 20
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_3_DMA_R_BW_3_BIT 21
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_3_DMA_W_DONE_3_BIT 22
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_3_DMA_W_BW_3_BIT 23
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_3_DMA_B_DONE_3_BIT 24
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_3_DMA_BUSY_3_BIT 25
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_3_ICACHE_MISS_3_BIT 26
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_3_ICACHE_HIT_3_BIT 27
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_3_ICACHE_PREFETCH_3_BIT 28
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_3_ICACHE_DOUBLE_HIT_3_BIT \
    29
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_3_ICACHE_STALL_3_BIT 30

// Enable particular performance counter and start tracking.
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_4_REG_OFFSET 0x20
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_4_CYCLE_4_BIT 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_4_TCDM_ACCESSED_4_BIT 1
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_4_TCDM_CONGESTED_4_BIT 2
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_4_ISSUE_FPU_4_BIT 3
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_4_ISSUE_FPU_SEQ_4_BIT 4
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_4_ISSUE_CORE_TO_FPU_4_BIT \
    5
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_4_RETIRED_INSTR_4_BIT 6
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_4_RETIRED_LOAD_4_BIT 7
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_4_RETIRED_I_4_BIT 8
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_4_RETIRED_ACC_4_BIT 9
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_4_DMA_AW_STALL_4_BIT 10
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_4_DMA_AR_STALL_4_BIT 11
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_4_DMA_R_STALL_4_BIT 12
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_4_DMA_W_STALL_4_BIT 13
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_4_DMA_BUF_W_STALL_4_BIT 14
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_4_DMA_BUF_R_STALL_4_BIT 15
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_4_DMA_AW_DONE_4_BIT 16
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_4_DMA_AW_BW_4_BIT 17
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_4_DMA_AR_DONE_4_BIT 18
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_4_DMA_AR_BW_4_BIT 19
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_4_DMA_R_DONE_4_BIT 20
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_4_DMA_R_BW_4_BIT 21
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_4_DMA_W_DONE_4_BIT 22
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_4_DMA_W_BW_4_BIT 23
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_4_DMA_B_DONE_4_BIT 24
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_4_DMA_BUSY_4_BIT 25
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_4_ICACHE_MISS_4_BIT 26
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_4_ICACHE_HIT_4_BIT 27
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_4_ICACHE_PREFETCH_4_BIT 28
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_4_ICACHE_DOUBLE_HIT_4_BIT \
    29
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_4_ICACHE_STALL_4_BIT 30

// Enable particular performance counter and start tracking.
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_5_REG_OFFSET 0x28
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_5_CYCLE_5_BIT 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_5_TCDM_ACCESSED_5_BIT 1
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_5_TCDM_CONGESTED_5_BIT 2
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_5_ISSUE_FPU_5_BIT 3
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_5_ISSUE_FPU_SEQ_5_BIT 4
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_5_ISSUE_CORE_TO_FPU_5_BIT \
    5
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_5_RETIRED_INSTR_5_BIT 6
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_5_RETIRED_LOAD_5_BIT 7
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_5_RETIRED_I_5_BIT 8
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_5_RETIRED_ACC_5_BIT 9
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_5_DMA_AW_STALL_5_BIT 10
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_5_DMA_AR_STALL_5_BIT 11
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_5_DMA_R_STALL_5_BIT 12
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_5_DMA_W_STALL_5_BIT 13
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_5_DMA_BUF_W_STALL_5_BIT 14
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_5_DMA_BUF_R_STALL_5_BIT 15
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_5_DMA_AW_DONE_5_BIT 16
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_5_DMA_AW_BW_5_BIT 17
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_5_DMA_AR_DONE_5_BIT 18
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_5_DMA_AR_BW_5_BIT 19
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_5_DMA_R_DONE_5_BIT 20
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_5_DMA_R_BW_5_BIT 21
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_5_DMA_W_DONE_5_BIT 22
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_5_DMA_W_BW_5_BIT 23
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_5_DMA_B_DONE_5_BIT 24
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_5_DMA_BUSY_5_BIT 25
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_5_ICACHE_MISS_5_BIT 26
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_5_ICACHE_HIT_5_BIT 27
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_5_ICACHE_PREFETCH_5_BIT 28
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_5_ICACHE_DOUBLE_HIT_5_BIT \
    29
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_5_ICACHE_STALL_5_BIT 30

// Enable particular performance counter and start tracking.
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_6_REG_OFFSET 0x30
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_6_CYCLE_6_BIT 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_6_TCDM_ACCESSED_6_BIT 1
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_6_TCDM_CONGESTED_6_BIT 2
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_6_ISSUE_FPU_6_BIT 3
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_6_ISSUE_FPU_SEQ_6_BIT 4
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_6_ISSUE_CORE_TO_FPU_6_BIT \
    5
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_6_RETIRED_INSTR_6_BIT 6
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_6_RETIRED_LOAD_6_BIT 7
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_6_RETIRED_I_6_BIT 8
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_6_RETIRED_ACC_6_BIT 9
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_6_DMA_AW_STALL_6_BIT 10
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_6_DMA_AR_STALL_6_BIT 11
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_6_DMA_R_STALL_6_BIT 12
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_6_DMA_W_STALL_6_BIT 13
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_6_DMA_BUF_W_STALL_6_BIT 14
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_6_DMA_BUF_R_STALL_6_BIT 15
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_6_DMA_AW_DONE_6_BIT 16
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_6_DMA_AW_BW_6_BIT 17
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_6_DMA_AR_DONE_6_BIT 18
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_6_DMA_AR_BW_6_BIT 19
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_6_DMA_R_DONE_6_BIT 20
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_6_DMA_R_BW_6_BIT 21
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_6_DMA_W_DONE_6_BIT 22
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_6_DMA_W_BW_6_BIT 23
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_6_DMA_B_DONE_6_BIT 24
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_6_DMA_BUSY_6_BIT 25
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_6_ICACHE_MISS_6_BIT 26
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_6_ICACHE_HIT_6_BIT 27
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_6_ICACHE_PREFETCH_6_BIT 28
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_6_ICACHE_DOUBLE_HIT_6_BIT \
    29
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_6_ICACHE_STALL_6_BIT 30

// Enable particular performance counter and start tracking.
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_7_REG_OFFSET 0x38
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_7_CYCLE_7_BIT 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_7_TCDM_ACCESSED_7_BIT 1
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_7_TCDM_CONGESTED_7_BIT 2
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_7_ISSUE_FPU_7_BIT 3
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_7_ISSUE_FPU_SEQ_7_BIT 4
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_7_ISSUE_CORE_TO_FPU_7_BIT \
    5
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_7_RETIRED_INSTR_7_BIT 6
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_7_RETIRED_LOAD_7_BIT 7
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_7_RETIRED_I_7_BIT 8
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_7_RETIRED_ACC_7_BIT 9
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_7_DMA_AW_STALL_7_BIT 10
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_7_DMA_AR_STALL_7_BIT 11
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_7_DMA_R_STALL_7_BIT 12
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_7_DMA_W_STALL_7_BIT 13
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_7_DMA_BUF_W_STALL_7_BIT 14
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_7_DMA_BUF_R_STALL_7_BIT 15
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_7_DMA_AW_DONE_7_BIT 16
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_7_DMA_AW_BW_7_BIT 17
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_7_DMA_AR_DONE_7_BIT 18
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_7_DMA_AR_BW_7_BIT 19
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_7_DMA_R_DONE_7_BIT 20
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_7_DMA_R_BW_7_BIT 21
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_7_DMA_W_DONE_7_BIT 22
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_7_DMA_W_BW_7_BIT 23
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_7_DMA_B_DONE_7_BIT 24
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_7_DMA_BUSY_7_BIT 25
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_7_ICACHE_MISS_7_BIT 26
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_7_ICACHE_HIT_7_BIT 27
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_7_ICACHE_PREFETCH_7_BIT 28
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_7_ICACHE_DOUBLE_HIT_7_BIT \
    29
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_ENABLE_7_ICACHE_STALL_7_BIT 30

// Select from which hart in the cluster, starting from `0`,
#define SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_HART_SELECT_FIELD_WIDTH 10
#define SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_HART_SELECT_FIELDS_PER_REG 6
#define SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_MULTIREG_COUNT 8

// Select from which hart in the cluster, starting from `0`,
#define SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_0_REG_OFFSET 0x40
#define SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_0_HART_SELECT_0_MASK 0x3ff
#define SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_0_HART_SELECT_0_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_0_HART_SELECT_0_FIELD         \
    ((bitfield_field32_t){                                                  \
        .mask = SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_0_HART_SELECT_0_MASK, \
        .index =                                                            \
            SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_0_HART_SELECT_0_OFFSET})

// Select from which hart in the cluster, starting from `0`,
#define SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_1_REG_OFFSET 0x48
#define SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_1_HART_SELECT_1_MASK 0x3ff
#define SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_1_HART_SELECT_1_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_1_HART_SELECT_1_FIELD         \
    ((bitfield_field32_t){                                                  \
        .mask = SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_1_HART_SELECT_1_MASK, \
        .index =                                                            \
            SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_1_HART_SELECT_1_OFFSET})

// Select from which hart in the cluster, starting from `0`,
#define SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_2_REG_OFFSET 0x50
#define SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_2_HART_SELECT_2_MASK 0x3ff
#define SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_2_HART_SELECT_2_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_2_HART_SELECT_2_FIELD         \
    ((bitfield_field32_t){                                                  \
        .mask = SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_2_HART_SELECT_2_MASK, \
        .index =                                                            \
            SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_2_HART_SELECT_2_OFFSET})

// Select from which hart in the cluster, starting from `0`,
#define SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_3_REG_OFFSET 0x58
#define SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_3_HART_SELECT_3_MASK 0x3ff
#define SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_3_HART_SELECT_3_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_3_HART_SELECT_3_FIELD         \
    ((bitfield_field32_t){                                                  \
        .mask = SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_3_HART_SELECT_3_MASK, \
        .index =                                                            \
            SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_3_HART_SELECT_3_OFFSET})

// Select from which hart in the cluster, starting from `0`,
#define SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_4_REG_OFFSET 0x60
#define SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_4_HART_SELECT_4_MASK 0x3ff
#define SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_4_HART_SELECT_4_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_4_HART_SELECT_4_FIELD         \
    ((bitfield_field32_t){                                                  \
        .mask = SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_4_HART_SELECT_4_MASK, \
        .index =                                                            \
            SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_4_HART_SELECT_4_OFFSET})

// Select from which hart in the cluster, starting from `0`,
#define SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_5_REG_OFFSET 0x68
#define SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_5_HART_SELECT_5_MASK 0x3ff
#define SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_5_HART_SELECT_5_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_5_HART_SELECT_5_FIELD         \
    ((bitfield_field32_t){                                                  \
        .mask = SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_5_HART_SELECT_5_MASK, \
        .index =                                                            \
            SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_5_HART_SELECT_5_OFFSET})

// Select from which hart in the cluster, starting from `0`,
#define SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_6_REG_OFFSET 0x70
#define SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_6_HART_SELECT_6_MASK 0x3ff
#define SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_6_HART_SELECT_6_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_6_HART_SELECT_6_FIELD         \
    ((bitfield_field32_t){                                                  \
        .mask = SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_6_HART_SELECT_6_MASK, \
        .index =                                                            \
            SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_6_HART_SELECT_6_OFFSET})

// Select from which hart in the cluster, starting from `0`,
#define SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_7_REG_OFFSET 0x78
#define SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_7_HART_SELECT_7_MASK 0x3ff
#define SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_7_HART_SELECT_7_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_7_HART_SELECT_7_FIELD         \
    ((bitfield_field32_t){                                                  \
        .mask = SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_7_HART_SELECT_7_MASK, \
        .index =                                                            \
            SNITCH_CLUSTER_PERIPHERAL_HART_SELECT_7_HART_SELECT_7_OFFSET})

// Performance counter. Set corresponding PERF_COUNTER_ENABLE bits depending
// on what
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_PERF_COUNTER_FIELD_WIDTH 48
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_PERF_COUNTER_FIELDS_PER_REG 1
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_MULTIREG_COUNT 8

// Performance counter. Set corresponding PERF_COUNTER_ENABLE bits depending
// on what
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_0_REG_OFFSET 0x80
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_0_PERF_COUNTER_0_MASK \
    0xffffffffffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_0_PERF_COUNTER_0_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_0_PERF_COUNTER_0_FIELD         \
    ((bitfield_field32_t){                                                    \
        .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_0_PERF_COUNTER_0_MASK, \
        .index =                                                              \
            SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_0_PERF_COUNTER_0_OFFSET})

// Performance counter. Set corresponding PERF_COUNTER_ENABLE bits depending
// on what
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_1_REG_OFFSET 0x88
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_1_PERF_COUNTER_1_MASK \
    0xffffffffffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_1_PERF_COUNTER_1_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_1_PERF_COUNTER_1_FIELD         \
    ((bitfield_field32_t){                                                    \
        .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_1_PERF_COUNTER_1_MASK, \
        .index =                                                              \
            SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_1_PERF_COUNTER_1_OFFSET})

// Performance counter. Set corresponding PERF_COUNTER_ENABLE bits depending
// on what
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_2_REG_OFFSET 0x90
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_2_PERF_COUNTER_2_MASK \
    0xffffffffffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_2_PERF_COUNTER_2_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_2_PERF_COUNTER_2_FIELD         \
    ((bitfield_field32_t){                                                    \
        .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_2_PERF_COUNTER_2_MASK, \
        .index =                                                              \
            SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_2_PERF_COUNTER_2_OFFSET})

// Performance counter. Set corresponding PERF_COUNTER_ENABLE bits depending
// on what
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_3_REG_OFFSET 0x98
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_3_PERF_COUNTER_3_MASK \
    0xffffffffffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_3_PERF_COUNTER_3_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_3_PERF_COUNTER_3_FIELD         \
    ((bitfield_field32_t){                                                    \
        .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_3_PERF_COUNTER_3_MASK, \
        .index =                                                              \
            SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_3_PERF_COUNTER_3_OFFSET})

// Performance counter. Set corresponding PERF_COUNTER_ENABLE bits depending
// on what
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_4_REG_OFFSET 0xa0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_4_PERF_COUNTER_4_MASK \
    0xffffffffffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_4_PERF_COUNTER_4_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_4_PERF_COUNTER_4_FIELD         \
    ((bitfield_field32_t){                                                    \
        .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_4_PERF_COUNTER_4_MASK, \
        .index =                                                              \
            SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_4_PERF_COUNTER_4_OFFSET})

// Performance counter. Set corresponding PERF_COUNTER_ENABLE bits depending
// on what
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_5_REG_OFFSET 0xa8
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_5_PERF_COUNTER_5_MASK \
    0xffffffffffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_5_PERF_COUNTER_5_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_5_PERF_COUNTER_5_FIELD         \
    ((bitfield_field32_t){                                                    \
        .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_5_PERF_COUNTER_5_MASK, \
        .index =                                                              \
            SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_5_PERF_COUNTER_5_OFFSET})

// Performance counter. Set corresponding PERF_COUNTER_ENABLE bits depending
// on what
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_6_REG_OFFSET 0xb0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_6_PERF_COUNTER_6_MASK \
    0xffffffffffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_6_PERF_COUNTER_6_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_6_PERF_COUNTER_6_FIELD         \
    ((bitfield_field32_t){                                                    \
        .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_6_PERF_COUNTER_6_MASK, \
        .index =                                                              \
            SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_6_PERF_COUNTER_6_OFFSET})

// Performance counter. Set corresponding PERF_COUNTER_ENABLE bits depending
// on what
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_7_REG_OFFSET 0xb8
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_7_PERF_COUNTER_7_MASK \
    0xffffffffffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_7_PERF_COUNTER_7_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_7_PERF_COUNTER_7_FIELD         \
    ((bitfield_field32_t){                                                    \
        .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_7_PERF_COUNTER_7_MASK, \
        .index =                                                              \
            SNITCH_CLUSTER_PERIPHERAL_PERF_COUNTER_7_PERF_COUNTER_7_OFFSET})

// Set bits in the cluster-local CLINT. Writing a 1 at location i sets the
// cluster-local interrupt
#define SNITCH_CLUSTER_PERIPHERAL_CL_CLINT_SET_REG_OFFSET 0xc0
#define SNITCH_CLUSTER_PERIPHERAL_CL_CLINT_SET_CL_CLINT_SET_MASK 0xffffffff
#define SNITCH_CLUSTER_PERIPHERAL_CL_CLINT_SET_CL_CLINT_SET_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_CL_CLINT_SET_CL_CLINT_SET_FIELD         \
    ((bitfield_field32_t){                                                \
        .mask = SNITCH_CLUSTER_PERIPHERAL_CL_CLINT_SET_CL_CLINT_SET_MASK, \
        .index = SNITCH_CLUSTER_PERIPHERAL_CL_CLINT_SET_CL_CLINT_SET_OFFSET})

// Clear bits in the cluster-local CLINT. Writing a 1 at location i clears
// the cluster-local interrupt
#define SNITCH_CLUSTER_PERIPHERAL_CL_CLINT_CLEAR_REG_OFFSET 0xc8
#define SNITCH_CLUSTER_PERIPHERAL_CL_CLINT_CLEAR_CL_CLINT_CLEAR_MASK 0xffffffff
#define SNITCH_CLUSTER_PERIPHERAL_CL_CLINT_CLEAR_CL_CLINT_CLEAR_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_CL_CLINT_CLEAR_CL_CLINT_CLEAR_FIELD         \
    ((bitfield_field32_t){                                                    \
        .mask = SNITCH_CLUSTER_PERIPHERAL_CL_CLINT_CLEAR_CL_CLINT_CLEAR_MASK, \
        .index =                                                              \
            SNITCH_CLUSTER_PERIPHERAL_CL_CLINT_CLEAR_CL_CLINT_CLEAR_OFFSET})

// Hardware barrier register. Loads to this register will block until all
// cores have
#define SNITCH_CLUSTER_PERIPHERAL_HW_BARRIER_REG_OFFSET 0xd0
#define SNITCH_CLUSTER_PERIPHERAL_HW_BARRIER_HW_BARRIER_MASK 0xffffffff
#define SNITCH_CLUSTER_PERIPHERAL_HW_BARRIER_HW_BARRIER_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_HW_BARRIER_HW_BARRIER_FIELD         \
    ((bitfield_field32_t){                                            \
        .mask = SNITCH_CLUSTER_PERIPHERAL_HW_BARRIER_HW_BARRIER_MASK, \
        .index = SNITCH_CLUSTER_PERIPHERAL_HW_BARRIER_HW_BARRIER_OFFSET})

// Controls prefetching of the instruction cache.
#define SNITCH_CLUSTER_PERIPHERAL_ICACHE_PREFETCH_ENABLE_REG_OFFSET 0xd8
#define SNITCH_CLUSTER_PERIPHERAL_ICACHE_PREFETCH_ENABLE_ICACHE_PREFETCH_ENABLE_BIT \
    0

#ifdef __cplusplus
}  // extern "C"
#endif
#endif  // _SNITCH_CLUSTER_PERIPHERAL_REG_DEFS_
        // End generated register defines for snitch_cluster_peripheral