  snitch_read_only_cache #(
    .LineWidth (${cfg["width"]}),
    .LineCount (${cfg["count"]}),
    .SetCount (${cfg["sets"]}),
    .AxiAddrWidth (${axi_in.aw}),
    .AxiDataWidth (${axi_in.dw}),
    .AxiIdWidth (${axi_in.iw}),
    .AxiUserWidth (${max(axi_in.uw, 1)}),
    .MaxTrans (${cfg["max_trans"]}),
    .NrAddrRules (${cfg["address_regions"]}),
    .slv_req_t (${axi_in.req_type()}),
    .slv_rsp_t (${axi_in.rsp_type()}),
    .mst_req_t (${axi_out.req_type()}),
    .mst_rsp_t (${axi_out.rsp_type()}),
    .sram_cfg_data_t (${sram_cfg_data_t}),
    .sram_cfg_tag_t (${sram_cfg_tag_t})
  ) ${name} (
    .clk_i (${axi_in.clk}),
    .rst_ni (${axi_in.rst}),
    .enable_i (${enable}),
    .flush_valid_i (${flush_valid}),
    .flush_ready_o (${flush_ready}),
    .start_addr_i (${start_addr}),
    .end_addr_i (${end_addr}),
    .axi_slv_req_i (${axi_in.req_name()}),
    .axi_slv_rsp_o (${axi_in.rsp_name()}),
    .axi_mst_req_o (${axi_out.req_name()}),
    .axi_mst_rsp_i (${axi_out.rsp_name()}),
    .sram_cfg_data_i (${sram_cfg_data_i}),
    .sram_cfg_tag_i (${sram_cfg_tag_i})
  );
