  typedef logic [${bus_in.iw}-${bus_out.iw}-1:0] ${name}_pre_id_t;
  axi_id_deprepend #(
    .slv_aw_chan_t  ( ${bus_in.type_prefix}_aw_chan_t ),
    .slv_w_chan_t   ( ${bus_in.type_prefix}_w_chan_t ),
    .slv_b_chan_t   ( ${bus_in.type_prefix}_b_chan_t ),
    .slv_ar_chan_t  ( ${bus_in.type_prefix}_ar_chan_t ),
    .slv_r_chan_t   ( ${bus_in.type_prefix}_r_chan_t ),
    .mst_aw_chan_t  ( ${bus_out.type_prefix}_aw_chan_t ),
    .mst_w_chan_t   ( ${bus_out.type_prefix}_w_chan_t ),
    .mst_b_chan_t   ( ${bus_out.type_prefix}_b_chan_t ),
    .mst_ar_chan_t  ( ${bus_out.type_prefix}_ar_chan_t ),
    .mst_r_chan_t   ( ${bus_out.type_prefix}_r_chan_t ),
    .NoBus          ( 1 ),
    .AxiIdWidthSlvPort ( ${bus_in.iw} ),
    .AxiIdWidthMstPort ( ${bus_out.iw} )
  ) ${name} (
    .pre_id_i           (${name}_pre_id_t'(${deprep_id})),
    .slv_aw_chans_i     (${bus_in.req_name()}.aw),
    .slv_aw_valids_i    (${bus_in.req_name()}.aw_valid),
    .slv_aw_readies_o   (${bus_in.rsp_name()}.aw_ready),
    .slv_w_chans_i      (${bus_in.req_name()}.w),
    .slv_w_valids_i     (${bus_in.req_name()}.w_valid),
    .slv_w_readies_o    (${bus_in.rsp_name()}.w_ready),
    .slv_b_chans_o      (${bus_in.rsp_name()}.b),
    .slv_b_valids_o     (${bus_in.rsp_name()}.b_valid),
    .slv_b_readies_i    (${bus_in.req_name()}.b_ready),
    .slv_ar_chans_i     (${bus_in.req_name()}.ar),
    .slv_ar_valids_i    (${bus_in.req_name()}.ar_valid),
    .slv_ar_readies_o   (${bus_in.rsp_name()}.ar_ready),
    .slv_r_chans_o      (${bus_in.rsp_name()}.r),
    .slv_r_valids_o     (${bus_in.rsp_name()}.r_valid),
    .slv_r_readies_i    (${bus_in.req_name()}.r_ready),
    .mst_aw_chans_o     (${bus_out.req_name()}.aw),
    .mst_aw_valids_o    (${bus_out.req_name()}.aw_valid),
    .mst_aw_readies_i   (${bus_out.rsp_name()}.aw_ready),
    .mst_w_chans_o      (${bus_out.req_name()}.w),
    .mst_w_valids_o     (${bus_out.req_name()}.w_valid),
    .mst_w_readies_i    (${bus_out.rsp_name()}.w_ready),
    .mst_b_chans_i      (${bus_out.rsp_name()}.b),
    .mst_b_valids_i     (${bus_out.rsp_name()}.b_valid),
    .mst_b_readies_o    (${bus_out.req_name()}.b_ready),
    .mst_ar_chans_o     (${bus_out.req_name()}.ar),
    .mst_ar_valids_o    (${bus_out.req_name()}.ar_valid),
    .mst_ar_readies_i   (${bus_out.rsp_name()}.ar_ready),
    .mst_r_chans_i      (${bus_out.rsp_name()}.r),
    .mst_r_valids_i     (${bus_out.rsp_name()}.r_valid),
    .mst_r_readies_o    (${bus_out.req_name()}.r_ready)
  );
