#!/bin/bash
# Copyright 2020 ETH Zurich and University of Bologna.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51

set -e
ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)

echo $ROOT
$ROOT/util/lowrisc_misc-linters/licence-checker/licence-checker.py --config $ROOT/util/licence-checker.hjson
