#!/bin/bash
# Copyright 2020 ETH Zurich and University of Bologna.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51

set -e
ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)

# Skip third party sources.
# TODO(zarubaf): Remove the package from the exclude.
find $ROOT/hw/ \
    -not \( -path '*.bender' -prune \) \
    -not \( -path $ROOT'/hw/vendor' -prune \) \
    -not \( -path $ROOT'/hw/system/occamy/fpga' -prune \) \
    -not \( -name 'snitch_pkg.sv' \) \
    -name '*.sv' \
    | xargs verible-verilog-lint \
    --rules=-interface-name-style --lint_fatal --parse_fatal \
    --waiver_files \
$ROOT/hw/ip/snitch_cluster/lint/waiver.verible,\
$ROOT/hw/system/occamy/lint/waiver.verible

