#!/bin/bash
# Copyright 2020 ETH Zurich and University of Bologna.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51

set -e
ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)

# Get all Bender.yml and format them. Exclude the vendor directory and hidden
# dirs.
find $ROOT \
    -not \( -path $ROOT/'hw/vendor' -prune \) \
    -not -path '*/\.bender/*' \
    -name '*.yml' | xargs yamlfmt -w
