# Copyright 2023 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# Luca Colagrande <colluca@iis.ee.ethz.ch>

SHARED_APPS_DIR  = $(abspath ../../../../../../sw/apps)
CLUSTER_APPS_DIR = $(abspath ..)

include $(SHARED_APPS_DIR)/lto/Makefile
include $(CLUSTER_APPS_DIR)/common.mk
