// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


`include "common_cells/assertions.svh"

module clint_reg_top #(
    parameter type reg_req_t = logic,
    parameter type reg_rsp_t = logic,
    parameter int AW = 16
) (
  input clk_i,
  input rst_ni,
  input  reg_req_t reg_req_i,
  output reg_rsp_t reg_rsp_o,
  // To HW
  output clint_reg_pkg::clint_reg2hw_t reg2hw, // Write
  input  clint_reg_pkg::clint_hw2reg_t hw2reg, // Read


  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);

  import clint_reg_pkg::* ;

  localparam int DW = 32;
  localparam int DBW = DW/8;                    // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [AW-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  // Below register interface can be changed
  reg_req_t  reg_intf_req;
  reg_rsp_t  reg_intf_rsp;


  assign reg_intf_req = reg_req_i;
  assign reg_rsp_o = reg_intf_rsp;


  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  assign reg_addr = reg_intf_req.addr;
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = (devmode_i & addrmiss) | wr_err;


  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic msip_p_0_qs;
  logic msip_p_0_wd;
  logic msip_p_0_we;
  logic msip_p_1_qs;
  logic msip_p_1_wd;
  logic msip_p_1_we;
  logic [31:0] mtimecmp_low0_qs;
  logic [31:0] mtimecmp_low0_wd;
  logic mtimecmp_low0_we;
  logic [31:0] mtimecmp_high0_qs;
  logic [31:0] mtimecmp_high0_wd;
  logic mtimecmp_high0_we;
  logic [31:0] mtimecmp_low1_qs;
  logic [31:0] mtimecmp_low1_wd;
  logic mtimecmp_low1_we;
  logic [31:0] mtimecmp_high1_qs;
  logic [31:0] mtimecmp_high1_wd;
  logic mtimecmp_high1_we;
  logic [31:0] mtime_low_qs;
  logic [31:0] mtime_low_wd;
  logic mtime_low_we;
  logic [31:0] mtime_high_qs;
  logic [31:0] mtime_high_wd;
  logic mtime_high_we;

  // Register instances

  // Subregister 0 of Multireg msip
  // R[msip]: V(False)

  // F[p_0]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_msip_p_0 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (msip_p_0_we),
    .wd     (msip_p_0_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.msip[0].q ),

    // to register interface (read)
    .qs     (msip_p_0_qs)
  );


  // F[p_1]: 1:1
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_msip_p_1 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (msip_p_1_we),
    .wd     (msip_p_1_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.msip[1].q ),

    // to register interface (read)
    .qs     (msip_p_1_qs)
  );



  // R[mtimecmp_low0]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RW"),
    .RESVAL  (32'h0)
  ) u_mtimecmp_low0 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (mtimecmp_low0_we),
    .wd     (mtimecmp_low0_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.mtimecmp_low0.q ),

    // to register interface (read)
    .qs     (mtimecmp_low0_qs)
  );


  // R[mtimecmp_high0]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RW"),
    .RESVAL  (32'h0)
  ) u_mtimecmp_high0 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (mtimecmp_high0_we),
    .wd     (mtimecmp_high0_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.mtimecmp_high0.q ),

    // to register interface (read)
    .qs     (mtimecmp_high0_qs)
  );


  // R[mtimecmp_low1]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RW"),
    .RESVAL  (32'h0)
  ) u_mtimecmp_low1 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (mtimecmp_low1_we),
    .wd     (mtimecmp_low1_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.mtimecmp_low1.q ),

    // to register interface (read)
    .qs     (mtimecmp_low1_qs)
  );


  // R[mtimecmp_high1]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RW"),
    .RESVAL  (32'h0)
  ) u_mtimecmp_high1 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (mtimecmp_high1_we),
    .wd     (mtimecmp_high1_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.mtimecmp_high1.q ),

    // to register interface (read)
    .qs     (mtimecmp_high1_qs)
  );


  // R[mtime_low]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RW"),
    .RESVAL  (32'h0)
  ) u_mtime_low (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (mtime_low_we),
    .wd     (mtime_low_wd),

    // from internal hardware
    .de     (hw2reg.mtime_low.de),
    .d      (hw2reg.mtime_low.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.mtime_low.q ),

    // to register interface (read)
    .qs     (mtime_low_qs)
  );


  // R[mtime_high]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RW"),
    .RESVAL  (32'h0)
  ) u_mtime_high (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (mtime_high_we),
    .wd     (mtime_high_wd),

    // from internal hardware
    .de     (hw2reg.mtime_high.de),
    .d      (hw2reg.mtime_high.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.mtime_high.q ),

    // to register interface (read)
    .qs     (mtime_high_qs)
  );




  logic [6:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[0] = (reg_addr == CLINT_MSIP_OFFSET);
    addr_hit[1] = (reg_addr == CLINT_MTIMECMP_LOW0_OFFSET);
    addr_hit[2] = (reg_addr == CLINT_MTIMECMP_HIGH0_OFFSET);
    addr_hit[3] = (reg_addr == CLINT_MTIMECMP_LOW1_OFFSET);
    addr_hit[4] = (reg_addr == CLINT_MTIMECMP_HIGH1_OFFSET);
    addr_hit[5] = (reg_addr == CLINT_MTIME_LOW_OFFSET);
    addr_hit[6] = (reg_addr == CLINT_MTIME_HIGH_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0 ;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[0] & (|(CLINT_PERMIT[0] & ~reg_be))) |
               (addr_hit[1] & (|(CLINT_PERMIT[1] & ~reg_be))) |
               (addr_hit[2] & (|(CLINT_PERMIT[2] & ~reg_be))) |
               (addr_hit[3] & (|(CLINT_PERMIT[3] & ~reg_be))) |
               (addr_hit[4] & (|(CLINT_PERMIT[4] & ~reg_be))) |
               (addr_hit[5] & (|(CLINT_PERMIT[5] & ~reg_be))) |
               (addr_hit[6] & (|(CLINT_PERMIT[6] & ~reg_be)))));
  end

  assign msip_p_0_we = addr_hit[0] & reg_we & !reg_error;
  assign msip_p_0_wd = reg_wdata[0];

  assign msip_p_1_we = addr_hit[0] & reg_we & !reg_error;
  assign msip_p_1_wd = reg_wdata[1];

  assign mtimecmp_low0_we = addr_hit[1] & reg_we & !reg_error;
  assign mtimecmp_low0_wd = reg_wdata[31:0];

  assign mtimecmp_high0_we = addr_hit[2] & reg_we & !reg_error;
  assign mtimecmp_high0_wd = reg_wdata[31:0];

  assign mtimecmp_low1_we = addr_hit[3] & reg_we & !reg_error;
  assign mtimecmp_low1_wd = reg_wdata[31:0];

  assign mtimecmp_high1_we = addr_hit[4] & reg_we & !reg_error;
  assign mtimecmp_high1_wd = reg_wdata[31:0];

  assign mtime_low_we = addr_hit[5] & reg_we & !reg_error;
  assign mtime_low_wd = reg_wdata[31:0];

  assign mtime_high_we = addr_hit[6] & reg_we & !reg_error;
  assign mtime_high_wd = reg_wdata[31:0];

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[0] = msip_p_0_qs;
        reg_rdata_next[1] = msip_p_1_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[31:0] = mtimecmp_low0_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[31:0] = mtimecmp_high0_qs;
      end

      addr_hit[3]: begin
        reg_rdata_next[31:0] = mtimecmp_low1_qs;
      end

      addr_hit[4]: begin
        reg_rdata_next[31:0] = mtimecmp_high1_qs;
      end

      addr_hit[5]: begin
        reg_rdata_next[31:0] = mtime_low_qs;
      end

      addr_hit[6]: begin
        reg_rdata_next[31:0] = mtime_high_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))

endmodule
